openapi: 3.0.3
info:
  title: shipping - Nodejs REST API backend - liveloads
  description: >-
    This is a sample REST API specification for a simple backend
    written in Nodejs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Choreo
  url: https://choreo.dev
servers:
  - url: http://localhost:9090
tags:
  - name: keys
    description: In-memory key-value cache API
paths:
  /shippingNotices:
    post:
      summary: add a shipping_notice
      operationId: SetNewShippingNotice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Header_Identifier:
                  type: string
                Header_ControlNumber:
                  type: string
                Header_Version:
                  type: string
                Header_DocumentType:
                  type: string
                ShipNotice_Identification:
                  type: string
                ShipNotice_Date:
                  type: string
                ShipNotice_Time:
                  type: string
                ShipNotice_TimeZone:
                  type: string
                HierarchicalLevel_Identification:
                  type: string
                HierarchicalLevel_HierarchicalID:
                  type: string
                HierarchicalLevel_HierarchicalParentID:
                  type: string
                HierarchicalLevel_HierarchicalLevelCode:
                  type: string
                ItemIdentification_Identification:
                  type: string
                ItemIdentification_ProductID:
                  type: string
                ItemIdentification_ProductDescription:
                  type: string
                ItemIdentification_ProductType:
                  type: string
                ItemIdentification_ProductCode:
                  type: string
                ItemDetail_Identification:
                  type: string
                ItemDetail_QuantityShipped:
                  type: string
                ItemDetail_PackagingInfo:
                  type: string
                ItemDetail_Weight:
                  type: string
                ItemDetail_WeightUnit:
                  type: string
                ProductDescription_Identification:
                  type: string
                ProductDescription_ItemDescription:
                  type: string
                ProductDescription_CharacteristicCode:
                  type: string
                ProductDescription_AdditionalInfo:
                  type: string
                ProductDescription_InfoQualifier:
                  type: string
                Name_Identification:
                  type: string
                Name_EntityIdentifierCode:
                  type: string
                Name_Name:
                  type: string
                Name_IdentificationCode:
                  type: string
                Name_IdentificationQualifier:
                  type: string
                TransactionTotals_Identification:
                  type: string
                TransactionTotals_NumberOfLineItems:
                  type: string
                TransactionTotals_HashTotal:
                  type: string
                TransactionTotals_WeightTotal:
                  type: string
                TransactionSetTrailer_Identification:
                  type: string
                TransactionSetTrailer_NumberOfIncludedSegments:
                  type: string
                TransactionSetTrailer_TransactionSetControlNumber:
                  type: string
      responses:
        "200":
          description: Successful operation
        "400":
          description: Invalid request body
      tags:
        - shipping_notices



