openapi: 3.0.3
info:
  title: shipping - Nodejs REST API backend - liveloads
  description: >-
    This is a sample REST API specification for a simple backend
    written in Nodejs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Choreo
  url: https://choreo.dev
servers:
  - url: http://localhost:9090
tags:
  - name: keys
    description: In-memory key-value cache API
paths:
  /shippingNotices:
    post:
      summary: add a shipping_notice
      operationId: SetNewShippingNotice
      responses:
        "200":
          description: Successful operation
        "400":
          description: Invalid request body
      tags:
        - shipping_notices



